- [ ] With changes in place the VM state publisher does not seem to be submitting the migrating payload
	- [ ] On this note, migration payload will not be sent for offline migration due to this being done by a sub-process call in zmigrate.


- Where is the pyxlz log? Al I can find is the history_logger?
- Attempt to put a payoad submission in the connected client inn the daemon init since the achiever class does not seem able to connect
- zmigrate cannot connect to pyxlz daemon, but it is running...? pyxlz log:

``` Bash
-- Subject: A start job for unit zynstra-pyxlzd.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit zynstra-pyxlzd.service has finished successfully.
--
-- The job identifier is 682781.
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]: 2023-09-05 11:32:56,314: [INFO]ZMF Logger - iaas-control-state-publisher - iaas-control-state-publisher: Base Client Standa>
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]: 2023-09-05 11:32:56,315: [INFO]ZMF Audit Logger - iaas-control-state-publisher - iaas-control-state-publisher: Base Client >
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]: 2023-09-05 11:32:56,316: [DEBUG]ZMF Logger - iaas-control-state-publisher - iaas-control-state-publisher: Logging Level set>
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]: 2023-09-05 11:32:56,322: [INFO]ZMF Logger - iaas-control-state-publisher - iaas-control-state-publisher: Nonblocking Connec>
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]: Traceback (most recent call last):
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]:   File "/usr/local/bin/pyxlz", line 8, in <module>
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]:     sys.exit(main())
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]:   File "/usr/local/lib/python3.8/dist-packages/pyxlz/__init__.py", line 475, in main
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]:     ec = getattr(sys.modules[__name__], command_line.mode+"_ap")(command_line, mode_args)
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]:   File "/usr/local/lib/python3.8/dist-packages/pyxlz/__init__.py", line 201, in daemon_ap
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]:     pyxlzd = daemon.pyxlzd(command_line)
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]:   File "/usr/local/lib/python3.8/dist-packages/pyxlz/daemon/__init__.py", line 186, in __init__
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]:     self.vm_state_pub.publish_migration_state(MigrationStates.NOT_MIGRATING)
Sep 05 11:32:56 zhapcon0000-008a-00-00 zynstra-pyxlzd[3595193]: TypeError: publish_migration_state() missing 1 required positional argument: 'migration_state'
```

4/5 
15
december

Go into office on 12th

AF is being spammed due to reconnections after  a disconnect error:
```
Default on_publish handler in Base_Client
yxlz.daemon.vmwatch.05e452ec-ed66-4a80-864a-35baa21458d7 - SRW - target state is MIGRATE so skipping monitor
ZMF Logger - iaas-control-state-publisher - iaas-control-state-publisher: On log callback message: Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b'iaas-control-state-publishe>
ZMF Logger - iaas-control-state-publisher - iaas-control-state-publisher: On log callback message: Received DISCONNECT None None
G]ZMF Audit Logger - iaas-control-state-publisher - iaas-control-state-publisher: Unexpected Disconnect | Error Code: 7, The connection was lost.
ZMF Logger - iaas-control-state-publisher - iaas-control-state-publisher: On log callback message: Received CONNACK (0, Success) properties=[]
MF Logger - iaas-control-state-publisher - iaas-control-state-publisher: Successfully Connected
ZMF Audit Logger - iaas-control-state-publisher - iaas-control-state-publisher: Unexpected Set of VM States. Skipping Publish | Service ID: SRV1 | Cu
```
